[nfe]
cnpj_cpf = "SEU_CNPJ_OU_CPF_AQUI"
caminho_certificado = "C:\\caminho\\para\\seu_certificado.pfx"
senha = "SENHA_DO_CERTIFICADO_AQUI"
caminho_relacao = "C:\\caminho\\para\\sua_planilha.xls"
pasta_xml = "C:\\caminho\\para\\pasta_xml"

[nfse]
usuario = "SEU_USUARIO_NFSE"
senha = "SUA_SENHA_NFSE"
caminho_cnpjs = "C:\\caminho\\para\\cnpjs.txt"
pasta_relatorio = "C:\\caminho\\para\\relatorios\\pdf"
